#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# MPL-2.0-ADDENDUM.md
# -------------------
# This project includes additional terms and clarifications that apply
# to this file. See MPL-2.0-ADDENDUM.md for details.

# Script to run REINS CLI from the installed package in .m2

M2_REPO="${HOME}/.m2/repository"
GROUP_PATH="br/com/dizeno"
ARTIFACT_ID="reins-nlce"
VERSION="0.0.1-SNAPSHOT"
MAIN_CLASS="br.com.dizeno.reins.run.cli.ReinsCli"

REINS_JAR="${M2_REPO}/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/${ARTIFACT_ID}-${VERSION}.jar"

if [ ! -f "${REINS_JAR}" ]; then
    echo "Error: REINS JAR not found at ${REINS_JAR}" >&2
    echo "Run 'mvn clean install' in the reins-nlce project first." >&2
    exit 1
fi

CLASSPATH="${REINS_JAR}"

# Add .m2 dependencies to Classpath if available
DEPENDENCIES=(
    "org/apache/maven/maven-plugin-api/3.9.6/maven-plugin-api-3.9.6.jar"
    "org/apache/maven/maven-model/3.9.6/maven-model-3.9.6.jar"
    "org/apache/maven/maven-artifact/3.9.6/maven-artifact-3.9.6.jar"
    "org/apache/maven/maven-core/3.9.6/maven-core-3.9.6.jar"
    "org/codehaus/plexus/plexus-utils/4.0.1/plexus-utils-4.0.1.jar"
    "org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar"
    "com/squareup/okhttp3/okhttp/4.12.0/okhttp-4.12.0.jar"
    "com/squareup/okio/okio/3.6.0/okio-3.6.0.jar"
    "com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0.jar"
    "org/jetbrains/kotlin/kotlin-stdlib/1.8.21/kotlin-stdlib-1.8.21.jar"
    "com/fasterxml/jackson/core/jackson-databind/2.17.2/jackson-databind-2.17.2.jar"
    "com/fasterxml/jackson/core/jackson-annotations/2.17.2/jackson-annotations-2.17.2.jar"
    "com/fasterxml/jackson/core/jackson-core/2.17.2/jackson-core-2.17.2.jar"
    "com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.17.2/jackson-datatype-jsr310-2.17.2.jar"
    "org/yaml/snakeyaml/2.2/snakeyaml-2.2.jar"
    "org/freemarker/freemarker/2.3.34/freemarker-2.3.34.jar"
    "io/github/java-diff-utils/java-diff-utils/4.15/java-diff-utils-4.15.jar"
    "io/smallrye/config/smallrye-config/3.8.3/smallrye-config-3.8.3.jar"
    "io/smallrye/config/smallrye-config-core/3.8.3/smallrye-config-core-3.8.3.jar"
    "io/smallrye/config/smallrye-config-common/3.8.3/smallrye-config-common-3.8.3.jar"
    "org/eclipse/microprofile/config/microprofile-config-api/3.1/microprofile-config-api-3.1.jar"
    "io/smallrye/common/smallrye-common-annotation/2.4.0/smallrye-common-annotation-2.4.0.jar"
    "io/smallrye/common/smallrye-common-expression/2.4.0/smallrye-common-expression-2.4.0.jar"
    "io/smallrye/common/smallrye-common-function/2.4.0/smallrye-common-function-2.4.0.jar"
    "io/smallrye/common/smallrye-common-constraint/2.4.0/smallrye-common-constraint-2.4.0.jar"
    "io/smallrye/common/smallrye-common-classloader/2.4.0/smallrye-common-classloader-2.4.0.jar"
    "org/jboss/logging/jboss-logging/3.6.0.Final/jboss-logging-3.6.0.Final.jar"
)

for dep in "${DEPENDENCIES[@]}"; do
    dep_path="${M2_REPO}/${dep}"
    if [ -f "${dep_path}" ]; then
        CLASSPATH="${CLASSPATH}:${dep_path}"
    fi
done

java -cp "${CLASSPATH}" "${MAIN_CLASS}" "$@"
